baseURL = "http://www.bookofmoons.com/"
title = "Book of Moons"
languageCode = "en"
theme = "minimage"
copyright = "Book of Moons (c) 2019"
disqusShortname = "book-of-moons"

[taxonomies]
category = "categories"
tag = "tags"

[[menu.global]]
  name = "Categories"
  url = "/categories"

[[menu.global]]
  name = "Fiction"
  url = "/categories/fiction/"

[[menu.global]]
  name = "Romance"
  url = "/categories/romance/"

[[menu.global]]
  name = "Horror"
  url = "/categories/horror/"

[[menu.global]]
  name = "Personal Development"
  url = "/categories/personal-development/"

[[menu.global]]
  name = "About"
  url = "/page/about"

[[menu.global]]
  name = "Write for us!"
  url = "https://docs.google.com/forms/d/15IUC1uZ66TIw3ErgUOKjWcFTJQW8EV-4w-1u2QXjOWQ/"

[[menu.footer]]
name = "About"
url = "/page/about"